apiVersion: v1
kind: Service
metadata:
  name: request-echo-svc
spec:
  selector:
    app: request-echo
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https-port
    protocol: TCP
    port: 8443
    targetPort: 8443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: request-echo-ingress-https
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: https
    appgw.ingress.kubernetes.io/rewrite-rule-set: app-a-rewrite-rule-set
    appgw.ingress.kubernetes.io/backend-hostname: api.jacobnosal.com
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/waf-policy-for-path: /subscriptions/10dc01bb-c96d-47d3-b553-338943349427/resourceGroups/rg-waf-policies/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/app-a-waf-policy
    # https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#appgw-trusted-root-certificate
    # appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: api.jacobnosal.com-trusted-root-cert
spec:
  tls:
  - hosts:
    - api.jacobnosal.com
    secretName: api.jacobnosal.com-tls
  rules:
  - host: api.jacobnosal.com
    http:
      paths:
      - path: /app-a
        backend:
          service:
            name: request-echo-svc
            port:
              number: 8443
        pathType: Prefix
---
apiVersion: v1
kind: Pod
metadata:
  name: request-echo-pod
  labels:
    app: request-echo
spec:
  volumes:
  - name: tls-certs
    secret:
      secretName: api.jacobnosal.com-tls
  containers:
  - image: jacobnosal/echo:v0.0.1
    name: request-echo
    env:
    - name: PRIVATE_KEY_FILE
      value: /var/echo/tls.key
    - name: FULLCHAIN_PEM_FILE
      value: /var/echo/tls.crt
    volumeMounts:
    - mountPath: /var/echo
      name: tls-certs
      readOnly: true
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 8443
      protocol: TCP