apiVersion: v1
kind: Pod
metadata:
  name: request-echo-pod
  labels:
    app: request-echo
spec:
  containers:
  - image: mendhak/http-https-echo:23
    name: request-echo
    ports:
    - containerPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: request-echo-svc
spec:
  selector:
    app: request-echo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: request-echo-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    # appgw.ingress.kubernetes.io/backend-protocol: https
    # include the WAF policy
    # appgw.ingress.kubernetes.io/waf-policy-for-path: /subscriptions/10dc01bb-c96d-47d3-b553-338943349427/resourceGroups/rg-waf-policies/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/app-a-waf-policy
    # Need a rewrite rule to chop off the /app-a
    appgw.ingress.kubernetes.io/rewrite-rule-set: app-a-rewrite-rule-set
    # appgw.ingress.kubernetes.io/ssl-redirect: "true"
    # appgw.ingress.kubernetes.io/backend-hostname: api.jacobnosal.com
    # # https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#appgw-ssl-certificate
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: api-jacobnosal-com-frontend-ssl
    # # https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#appgw-trusted-root-certificate
    # appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: api.jacobnosal.com-trusted-root-cert
spec:
  rules:
  - host: api.jacobnosal.com
    http:
      paths:
      - path: /app-a
        backend:
          service:
            name: request-echo-svc
            port:
              number: 8080
        pathType: Prefix

